@startuml
class kaisafe.data.Instruction {
- int id
- java.lang.String title
- java.lang.String content
+ int getId()
+ java.lang.String getTitle()
+ java.lang.String getContent()
+ int component1()
+ java.lang.String component2()
+ java.lang.String component3()
+ kaisafe.data.Instruction copy(int,java.lang.String,java.lang.String)
+ boolean equals(java.lang.Object)
+ int hashCode()
+ java.lang.String toString()
}


class kaisafe.data.ContactRepository {
- kaisafe.data.ContactDao dao
- androidx.lifecycle.LiveData<java.util.List<kaisafe.data.ContactEntity>> allContacts
+ androidx.lifecycle.LiveData<java.util.List<kaisafe.data.ContactEntity>> getAllContacts()
+ java.lang.Object insertAll(java.util.List<kaisafe.data.ContactEntity>,kotlin.coroutines.Continuation<? super kotlin.Unit>)
+ java.lang.Object getAllOnce(kotlin.coroutines.Continuation<? super java.util.List<kaisafe.data.ContactEntity>>)
}


class kaisafe.MainActivity {
- kaisafe.databinding.ActivityMainBinding binding
# void onCreate(android.os.Bundle)
}


class kaisafe.ui.map.MapFragment {
- FragmentMapBinding? _binding
-  binding
+ View onCreateView(LayoutInflater,ViewGroup?,Bundle?)
+ void onDestroyView()
}


class kaisafe.data.ContactEntity {
- int id
- java.lang.String name
- java.lang.String phone
+ int getId()
+ java.lang.String getName()
+ java.lang.String getPhone()
+ int component1()
+ java.lang.String component2()
+ java.lang.String component3()
+ kaisafe.data.ContactEntity copy(int,java.lang.String,java.lang.String)
+ boolean equals(java.lang.Object)
+ int hashCode()
+ java.lang.String toString()
}


class kaisafe.ui.home.InstructionViewModel {
- InstructionRepository repository
+ LiveData<List<Instruction>> allInstructions
}

class kaisafe.databinding.ActivityMainBinding {
- ConstraintLayout rootView
+ ConstraintLayout container
+ BottomNavigationView navView
+ ConstraintLayout getRoot()
+ {static} ActivityMainBinding inflate(LayoutInflater)
+ {static} ActivityMainBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} ActivityMainBinding bind(View)
}


class kaisafe.data.ContactRepository {
+ LiveData<List<ContactEntity>> allContacts
+ void insertAll(List<ContactEntity>)
+ List<ContactEntity> getAllOnce()
}


class kaisafe.ui.home.InstructionDetailFragment {
- kaisafe.databinding.FragmentInstructionDetailBinding _binding
- kaisafe.databinding.FragmentInstructionDetailBinding getBinding()
+ void onCreate(android.os.Bundle)
+ android.view.View onCreateView(android.view.LayoutInflater,android.view.ViewGroup,android.os.Bundle)
+ void onViewCreated(android.view.View,android.os.Bundle)
+ boolean onOptionsItemSelected(android.view.MenuItem)
+ void onDestroyView()
}


class kaisafe.ui.home.InstructionDetailFragment {
- FragmentInstructionDetailBinding? _binding
-  binding
+ void onCreate(Bundle?)
+ View onCreateView(LayoutInflater,ViewGroup?,Bundle?)
+ void onViewCreated(View,Bundle?)
+ Boolean onOptionsItemSelected(MenuItem)
+ void onDestroyView()
}


class kaisafe.ui.contacts.ContactsAdapter {
- java.util.List<kaisafe.data.ContactEntity> contacts
+ kaisafe.ui.contacts.ContactsAdapter.ContactViewHolder onCreateViewHolder(android.view.ViewGroup,int)
+ void onBindViewHolder(kaisafe.ui.contacts.ContactsAdapter.ContactViewHolder,int)
+ int getItemCount()
}


class kaisafe.ui.contacts.ContactsAdapter$ContactViewHolder {
- kaisafe.databinding.ItemContactBinding binding
+ kaisafe.databinding.ItemContactBinding getBinding()
}


class kaisafe.ui.map.MapFragment {
- kaisafe.databinding.FragmentMapBinding _binding
- kaisafe.databinding.FragmentMapBinding getBinding()
+ android.view.View onCreateView(android.view.LayoutInflater,android.view.ViewGroup,android.os.Bundle)
+ void onDestroyView()
}


class kaisafe.data.InstructionRepository {
+ LiveData<List<Instruction>> allInstructions
+ void insertAll(List<Instruction>)
+ List<Instruction> getAllOnce()
}


class kaisafe.ui.contacts.ContactsFragment {
- kaisafe.databinding.FragmentContactsBinding _binding
- kotlin.Lazy viewModel$delegate
- kaisafe.databinding.FragmentContactsBinding getBinding()
- kaisafe.ui.contacts.ContactsViewModel getViewModel()
+ android.view.View onCreateView(android.view.LayoutInflater,android.view.ViewGroup,android.os.Bundle)
+ void onDestroyView()
}


class kaisafe.data.AppDB$Companion {
- AppDB? INSTANCE
+ AppDB getDatabase(Context)
}


abstract class kaisafe.data.AppDB {
+ InstructionDao instructionDao()
+ ContactDao contactDao()
}

class kaisafe.databinding.ItemContactBinding {
- CardView rootView
+ Button buttonCall
+ ImageView contactIcon
+ TextView contactName
+ TextView contactPhone
+ CardView getRoot()
+ {static} ItemContactBinding inflate(LayoutInflater)
+ {static} ItemContactBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} ItemContactBinding bind(View)
}


class kaisafe.ui.contacts.ContactsViewModel {
- kaisafe.data.ContactRepository repository
- androidx.lifecycle.LiveData<java.util.List<kaisafe.data.ContactEntity>> allContacts
+ androidx.lifecycle.LiveData<java.util.List<kaisafe.data.ContactEntity>> getAllContacts()
}


class kaisafe.databinding.FragmentMapBinding {
- ScrollView rootView
+ PhotoView mapImage1
+ PhotoView mapImage2
+ ScrollView getRoot()
+ {static} FragmentMapBinding inflate(LayoutInflater)
+ {static} FragmentMapBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} FragmentMapBinding bind(View)
}


class kaisafe.data.Instruction {
- int id
- java.lang.String title
- java.lang.String content
+ int getId()
+ java.lang.String getTitle()
+ java.lang.String getContent()
+ int component1()
+ java.lang.String component2()
+ java.lang.String component3()
+ kaisafe.data.Instruction copy(int,java.lang.String,java.lang.String)
+ boolean equals(java.lang.Object)
+ int hashCode()
+ java.lang.String toString()
}


class kaisafe.ui.home.InstructionAdapter {
- java.util.List<kaisafe.data.Instruction> instructions
+ kaisafe.ui.home.InstructionAdapter.ViewHolder onCreateViewHolder(android.view.ViewGroup,int)
+ void onBindViewHolder(kaisafe.ui.home.InstructionAdapter.ViewHolder,int)
+ int getItemCount()
+ void updateData(java.util.List<kaisafe.data.Instruction>)
}


class kaisafe.ui.home.InstructionAdapter$ViewHolder {
- android.widget.TextView title
+ android.widget.TextView getTitle()
}


interface kaisafe.data.InstructionDao {
+ {abstract}androidx.lifecycle.LiveData<java.util.List<kaisafe.data.Instruction>> getAll()
+ {abstract}java.lang.Object getAllOnce(kotlin.coroutines.Continuation<? super java.util.List<kaisafe.data.Instruction>>)
+ {abstract}java.lang.Object insertAll(java.util.List<kaisafe.data.Instruction>,kotlin.coroutines.Continuation<? super kotlin.Unit>)
}

class kaisafe.ui.map.MapViewModel {
-  _text
+ LiveData<String> text
}

class kaisafe.ui.home.HomeFragment {
- InstructionViewModel viewModel
- InstructionAdapter adapter
+ View? onCreateView(LayoutInflater,ViewGroup?,Bundle?)
}


class kaisafe.data.InstructionDao_Impl {
- RoomDatabase __db
- EntityInsertionAdapter<Instruction> __insertionAdapterOfInstruction
+ Object insertAll(List<Instruction>,Continuation<? super Unit>)
+ LiveData<List<Instruction>> getAll()
+ Object getAllOnce(Continuation<? super List<Instruction>>)
+ {static} List<Class<?>> getRequiredConverters()
}


class kaisafe.ui.home.InstructionViewModel {
- kaisafe.data.InstructionRepository repository
- androidx.lifecycle.LiveData<java.util.List<kaisafe.data.Instruction>> allInstructions
+ androidx.lifecycle.LiveData<java.util.List<kaisafe.data.Instruction>> getAllInstructions()
}


interface kaisafe.data.InstructionDao {
+ LiveData<List<Instruction>> getAll()
+ List<Instruction> getAllOnce()
+ void insertAll(List<Instruction>)
}

class kaisafe.MainActivity {
- ActivityMainBinding binding
+ void onCreate(Bundle?)
}


class kaisafe.databinding.FragmentHomeBinding {
- ConstraintLayout rootView
+ RecyclerView recyclerInstructions
+ ConstraintLayout getRoot()
+ {static} FragmentHomeBinding inflate(LayoutInflater)
+ {static} FragmentHomeBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} FragmentHomeBinding bind(View)
}


class kaisafe.ui.home.InstructionAdapter$ViewHolder {
+ TextView title
}

class kaisafe.ui.home.InstructionAdapter {
+ ViewHolder onCreateViewHolder(ViewGroup,Int)
+ void onBindViewHolder(ViewHolder,Int)
+ void getItemCount()
+ void updateData(List<Instruction>)
}

class kaisafe.databinding.FragmentHomeBinding {
- ConstraintLayout rootView
+ RecyclerView recyclerInstructions
+ ConstraintLayout getRoot()
+ {static} FragmentHomeBinding inflate(LayoutInflater)
+ {static} FragmentHomeBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} FragmentHomeBinding bind(View)
}


interface kaisafe.data.ContactDao {
+ {abstract}androidx.lifecycle.LiveData<java.util.List<kaisafe.data.ContactEntity>> getAll()
+ {abstract}java.lang.Object getAllOnce(kotlin.coroutines.Continuation<? super java.util.List<kaisafe.data.ContactEntity>>)
+ {abstract}java.lang.Object insertAll(java.util.List<kaisafe.data.ContactEntity>,kotlin.coroutines.Continuation<? super kotlin.Unit>)
}

class kaisafe.databinding.FragmentInstructionDetailBinding {
- ScrollView rootView
+ TextView textContent
+ TextView textTitle
+ ScrollView getRoot()
+ {static} FragmentInstructionDetailBinding inflate(LayoutInflater)
+ {static} FragmentInstructionDetailBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} FragmentInstructionDetailBinding bind(View)
}


class kaisafe.ui.home.InstructionViewModel {
- kaisafe.data.InstructionRepository repository
- androidx.lifecycle.LiveData<java.util.List<kaisafe.data.Instruction>> allInstructions
+ androidx.lifecycle.LiveData<java.util.List<kaisafe.data.Instruction>> getAllInstructions()
}


class kaisafe.databinding.FragmentInstructionDetailBinding {
- ScrollView rootView
+ TextView textContent
+ TextView textTitle
+ ScrollView getRoot()
+ {static} FragmentInstructionDetailBinding inflate(LayoutInflater)
+ {static} FragmentInstructionDetailBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} FragmentInstructionDetailBinding bind(View)
}


class kaisafe.ui.contacts.ContactsFragment {
- kaisafe.databinding.FragmentContactsBinding _binding
- kotlin.Lazy viewModel$delegate
- kaisafe.databinding.FragmentContactsBinding getBinding()
- kaisafe.ui.contacts.ContactsViewModel getViewModel()
+ android.view.View onCreateView(android.view.LayoutInflater,android.view.ViewGroup,android.os.Bundle)
+ void onDestroyView()
}


class kaisafe.ui.map.MapViewModel {
- androidx.lifecycle.MutableLiveData<java.lang.String> _text
- androidx.lifecycle.LiveData<java.lang.String> text
+ androidx.lifecycle.LiveData<java.lang.String> getText()
}


class kaisafe.data.AppDB_Impl {
- InstructionDao _instructionDao
- ContactDao _contactDao
# SupportSQLiteOpenHelper createOpenHelper(DatabaseConfiguration)
# InvalidationTracker createInvalidationTracker()
+ void clearAllTables()
# Map<Class<?>,List<Class<?>>> getRequiredTypeConverters()
+ Set<Class<? extends AutoMigrationSpec>> getRequiredAutoMigrationSpecs()
+ List<Migration> getAutoMigrations(Map<Class<? extends AutoMigrationSpec>,AutoMigrationSpec>)
+ InstructionDao instructionDao()
+ ContactDao contactDao()
}


class kaisafe.databinding.FragmentContactsBinding {
- ConstraintLayout rootView
+ RecyclerView recyclerContacts
+ ConstraintLayout getRoot()
+ {static} FragmentContactsBinding inflate(LayoutInflater)
+ {static} FragmentContactsBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} FragmentContactsBinding bind(View)
}


abstract class kaisafe.data.AppDB {
- {static} kaisafe.data.AppDB INSTANCE
+ {static} kaisafe.data.AppDB.Companion Companion
+ {abstract}kaisafe.data.InstructionDao instructionDao()
+ {abstract}kaisafe.data.ContactDao contactDao()
}


class kaisafe.data.AppDB$Companion {
+ kaisafe.data.AppDB getDatabase(android.content.Context)
}

class error.NonExistentClass {
}
class kaisafe.databinding.FragmentContactsBinding {
- ConstraintLayout rootView
+ RecyclerView recyclerContacts
+ ConstraintLayout getRoot()
+ {static} FragmentContactsBinding inflate(LayoutInflater)
+ {static} FragmentContactsBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} FragmentContactsBinding bind(View)
}


abstract class kaisafe.data.AppDB {
- {static} kaisafe.data.AppDB INSTANCE
+ {static} kaisafe.data.AppDB.Companion Companion
+ {abstract}kaisafe.data.InstructionDao instructionDao()
+ {abstract}kaisafe.data.ContactDao contactDao()
}


class kaisafe.data.AppDB$Companion {
+ kaisafe.data.AppDB getDatabase(android.content.Context)
}

class kaisafe.data.InstructionRepository {
- kaisafe.data.InstructionDao dao
- androidx.lifecycle.LiveData<java.util.List<kaisafe.data.Instruction>> allInstructions
+ androidx.lifecycle.LiveData<java.util.List<kaisafe.data.Instruction>> getAllInstructions()
+ java.lang.Object insertAll(java.util.List<kaisafe.data.Instruction>,kotlin.coroutines.Continuation<? super kotlin.Unit>)
+ java.lang.Object getAllOnce(kotlin.coroutines.Continuation<? super java.util.List<kaisafe.data.Instruction>>)
}


class kaisafe.ui.contacts.ContactsViewModel {
- ContactRepository repository
+ LiveData<List<ContactEntity>> allContacts
}

interface kaisafe.data.ContactDao {
+ {abstract}androidx.lifecycle.LiveData<java.util.List<kaisafe.data.ContactEntity>> getAll()
+ {abstract}java.lang.Object getAllOnce(kotlin.coroutines.Continuation<? super java.util.List<kaisafe.data.ContactEntity>>)
+ {abstract}java.lang.Object insertAll(java.util.List<kaisafe.data.ContactEntity>,kotlin.coroutines.Continuation<? super kotlin.Unit>)
}

class kaisafe.ui.contacts.ContactsFragment {
- FragmentContactsBinding? _binding
-  binding
- ContactsViewModel viewModel
+ View onCreateView(LayoutInflater,ViewGroup?,Bundle?)
+ void onDestroyView()
}


class kaisafe.ui.home.HomeFragment {
- kotlin.Lazy viewModel$delegate
- kaisafe.ui.home.InstructionAdapter adapter
- kaisafe.ui.home.InstructionViewModel getViewModel()
+ android.view.View onCreateView(android.view.LayoutInflater,android.view.ViewGroup,android.os.Bundle)
}


class kaisafe.databinding.ActivityMainBinding {
- ConstraintLayout rootView
+ ConstraintLayout container
+ BottomNavigationView navView
+ ConstraintLayout getRoot()
+ {static} ActivityMainBinding inflate(LayoutInflater)
+ {static} ActivityMainBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} ActivityMainBinding bind(View)
}


interface kaisafe.data.InstructionDao {
+ {abstract}androidx.lifecycle.LiveData<java.util.List<kaisafe.data.Instruction>> getAll()
+ {abstract}java.lang.Object getAllOnce(kotlin.coroutines.Continuation<? super java.util.List<kaisafe.data.Instruction>>)
+ {abstract}java.lang.Object insertAll(java.util.List<kaisafe.data.Instruction>,kotlin.coroutines.Continuation<? super kotlin.Unit>)
}

class kaisafe.ui.contacts.ContactsAdapter {
- java.util.List<kaisafe.data.ContactEntity> contacts
+ kaisafe.ui.contacts.ContactsAdapter.ContactViewHolder onCreateViewHolder(android.view.ViewGroup,int)
+ void onBindViewHolder(kaisafe.ui.contacts.ContactsAdapter.ContactViewHolder,int)
+ int getItemCount()
}


class kaisafe.ui.contacts.ContactsAdapter$ContactViewHolder {
- kaisafe.databinding.ItemContactBinding binding
+ kaisafe.databinding.ItemContactBinding getBinding()
}


class kaisafe.data.AppDB_Impl {
- InstructionDao _instructionDao
- ContactDao _contactDao
# SupportSQLiteOpenHelper createOpenHelper(DatabaseConfiguration)
# InvalidationTracker createInvalidationTracker()
+ void clearAllTables()
# Map<Class<?>,List<Class<?>>> getRequiredTypeConverters()
+ Set<Class<? extends AutoMigrationSpec>> getRequiredAutoMigrationSpecs()
+ List<Migration> getAutoMigrations(Map<Class<? extends AutoMigrationSpec>,AutoMigrationSpec>)
+ InstructionDao instructionDao()
+ ContactDao contactDao()
}


class kaisafe.ExampleInstrumentedTest {
+ void useAppContext()
}

class error.NonExistentClass {
}
class kaisafe.ui.contacts.ContactsAdapter$ContactViewHolder {
}
class kaisafe.ui.contacts.ContactsAdapter {
+ ContactViewHolder onCreateViewHolder(ViewGroup,Int)
+ void onBindViewHolder(ContactViewHolder,Int)
+ void getItemCount()
}

class kaisafe.ui.contacts.ContactsViewModel {
- kaisafe.data.ContactRepository repository
- androidx.lifecycle.LiveData<java.util.List<kaisafe.data.ContactEntity>> allContacts
+ androidx.lifecycle.LiveData<java.util.List<kaisafe.data.ContactEntity>> getAllContacts()
}


class kaisafe.data.ContactEntity {
- int id
- java.lang.String name
- java.lang.String phone
+ int getId()
+ java.lang.String getName()
+ java.lang.String getPhone()
+ int component1()
+ java.lang.String component2()
+ java.lang.String component3()
+ kaisafe.data.ContactEntity copy(int,java.lang.String,java.lang.String)
+ boolean equals(java.lang.Object)
+ int hashCode()
+ java.lang.String toString()
}


class kaisafe.data.ContactEntity {
}
class kaisafe.databinding.ItemInstructionBinding {
- CardView rootView
+ TextView textDescription
+ TextView textTitle
+ CardView getRoot()
+ {static} ItemInstructionBinding inflate(LayoutInflater)
+ {static} ItemInstructionBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} ItemInstructionBinding bind(View)
}


class kaisafe.ui.map.MapFragment {
- kaisafe.databinding.FragmentMapBinding _binding
- kaisafe.databinding.FragmentMapBinding getBinding()
+ android.view.View onCreateView(android.view.LayoutInflater,android.view.ViewGroup,android.os.Bundle)
+ void onDestroyView()
}


class kaisafe.data.InstructionDao_Impl {
- RoomDatabase __db
- EntityInsertionAdapter<Instruction> __insertionAdapterOfInstruction
+ Object insertAll(List<Instruction>,Continuation<? super Unit>)
+ LiveData<List<Instruction>> getAll()
+ Object getAllOnce(Continuation<? super List<Instruction>>)
+ {static} List<Class<?>> getRequiredConverters()
}


class kaisafe.databinding.ItemContactBinding {
- CardView rootView
+ Button buttonCall
+ ImageView contactIcon
+ TextView contactName
+ TextView contactPhone
+ CardView getRoot()
+ {static} ItemContactBinding inflate(LayoutInflater)
+ {static} ItemContactBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} ItemContactBinding bind(View)
}


class kaisafe.data.ContactDao_Impl {
- RoomDatabase __db
- EntityInsertionAdapter<ContactEntity> __insertionAdapterOfContactEntity
+ Object insertAll(List<ContactEntity>,Continuation<? super Unit>)
+ LiveData<List<ContactEntity>> getAll()
+ Object getAllOnce(Continuation<? super List<ContactEntity>>)
+ {static} List<Class<?>> getRequiredConverters()
}


class kaisafe.databinding.FragmentMapBinding {
- ScrollView rootView
+ PhotoView mapImage1
+ PhotoView mapImage2
+ ScrollView getRoot()
+ {static} FragmentMapBinding inflate(LayoutInflater)
+ {static} FragmentMapBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} FragmentMapBinding bind(View)
}


class kaisafe.ui.map.MapViewModel {
- androidx.lifecycle.MutableLiveData<java.lang.String> _text
- androidx.lifecycle.LiveData<java.lang.String> text
+ androidx.lifecycle.LiveData<java.lang.String> getText()
}


class kaisafe.ui.home.HomeFragment {
- kotlin.Lazy viewModel$delegate
- kaisafe.ui.home.InstructionAdapter adapter
- kaisafe.ui.home.InstructionViewModel getViewModel()
+ android.view.View onCreateView(android.view.LayoutInflater,android.view.ViewGroup,android.os.Bundle)
}


class kaisafe.data.Instruction {
}
class kaisafe.ui.home.InstructionAdapter {
- java.util.List<kaisafe.data.Instruction> instructions
+ kaisafe.ui.home.InstructionAdapter.ViewHolder onCreateViewHolder(android.view.ViewGroup,int)
+ void onBindViewHolder(kaisafe.ui.home.InstructionAdapter.ViewHolder,int)
+ int getItemCount()
+ void updateData(java.util.List<kaisafe.data.Instruction>)
}


class kaisafe.ui.home.InstructionAdapter$ViewHolder {
- android.widget.TextView title
+ android.widget.TextView getTitle()
}


class kaisafe.data.ContactRepository {
- kaisafe.data.ContactDao dao
- androidx.lifecycle.LiveData<java.util.List<kaisafe.data.ContactEntity>> allContacts
+ androidx.lifecycle.LiveData<java.util.List<kaisafe.data.ContactEntity>> getAllContacts()
+ java.lang.Object insertAll(java.util.List<kaisafe.data.ContactEntity>,kotlin.coroutines.Continuation<? super kotlin.Unit>)
+ java.lang.Object getAllOnce(kotlin.coroutines.Continuation<? super java.util.List<kaisafe.data.ContactEntity>>)
}


class kaisafe.data.ContactDao_Impl {
- RoomDatabase __db
- EntityInsertionAdapter<ContactEntity> __insertionAdapterOfContactEntity
+ Object insertAll(List<ContactEntity>,Continuation<? super Unit>)
+ LiveData<List<ContactEntity>> getAll()
+ Object getAllOnce(Continuation<? super List<ContactEntity>>)
+ {static} List<Class<?>> getRequiredConverters()
}


class kaisafe.ui.home.InstructionDetailFragment {
- kaisafe.databinding.FragmentInstructionDetailBinding _binding
- kaisafe.databinding.FragmentInstructionDetailBinding getBinding()
+ void onCreate(android.os.Bundle)
+ android.view.View onCreateView(android.view.LayoutInflater,android.view.ViewGroup,android.os.Bundle)
+ void onViewCreated(android.view.View,android.os.Bundle)
+ boolean onOptionsItemSelected(android.view.MenuItem)
+ void onDestroyView()
}


class kaisafe.databinding.ItemInstructionBinding {
- CardView rootView
+ TextView textDescription
+ TextView textTitle
+ CardView getRoot()
+ {static} ItemInstructionBinding inflate(LayoutInflater)
+ {static} ItemInstructionBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} ItemInstructionBinding bind(View)
}


class kaisafe.MainActivity {
- kaisafe.databinding.ActivityMainBinding binding
# void onCreate(android.os.Bundle)
}


interface kaisafe.data.ContactDao {
+ LiveData<List<ContactEntity>> getAll()
+ List<ContactEntity> getAllOnce()
+ void insertAll(List<ContactEntity>)
}

class kaisafe.ExampleUnitTest {
+ void addition_isCorrect()
}

class kaisafe.data.InstructionRepository {
- kaisafe.data.InstructionDao dao
- androidx.lifecycle.LiveData<java.util.List<kaisafe.data.Instruction>> allInstructions
+ androidx.lifecycle.LiveData<java.util.List<kaisafe.data.Instruction>> getAllInstructions()
+ java.lang.Object insertAll(java.util.List<kaisafe.data.Instruction>,kotlin.coroutines.Continuation<? super kotlin.Unit>)
+ java.lang.Object getAllOnce(kotlin.coroutines.Continuation<? super java.util.List<kaisafe.data.Instruction>>)
}




kaisafe.AppCompatActivity <|-- kaisafe.MainActivity
androidx.fragment.app.Fragment <|-- kaisafe.ui.map.MapFragment
androidx.lifecycle.AndroidViewModel <|-- kaisafe.ui.home.InstructionViewModel
androidx.viewbinding.ViewBinding <|.. kaisafe.databinding.ActivityMainBinding
kaisafe.ui.home.Fragment <|-- kaisafe.ui.home.InstructionDetailFragment
androidx.fragment.app.Fragment <|-- kaisafe.ui.home.InstructionDetailFragment
kaisafe.ui.contacts.Adapter <|-- kaisafe.ui.contacts.ContactsAdapter
kaisafe.ui.contacts.ContactsAdapter +.. kaisafe.ui.contacts.ContactsAdapter$ContactViewHolder
kaisafe.ui.contacts.ViewHolder <|-- kaisafe.ui.contacts.ContactsAdapter$ContactViewHolder
kaisafe.ui.map.Fragment <|-- kaisafe.ui.map.MapFragment
kaisafe.ui.contacts.Fragment <|-- kaisafe.ui.contacts.ContactsFragment
kaisafe.data.AppDB +.. kaisafe.data.AppDB$Companion
androidx.room.RoomDatabase <|-- kaisafe.data.AppDB
androidx.viewbinding.ViewBinding <|.. kaisafe.databinding.ItemContactBinding
kaisafe.ui.contacts.AndroidViewModel <|-- kaisafe.ui.contacts.ContactsViewModel
androidx.viewbinding.ViewBinding <|.. kaisafe.databinding.FragmentMapBinding
kaisafe.ui.home.Adapter <|-- kaisafe.ui.home.InstructionAdapter
kaisafe.ui.home.InstructionAdapter +.. kaisafe.ui.home.InstructionAdapter$ViewHolder
kaisafe.ui.home.ViewHolder <|-- kaisafe.ui.home.InstructionAdapter$ViewHolder
androidx.lifecycle.ViewModel <|-- kaisafe.ui.map.MapViewModel
androidx.fragment.app.Fragment <|-- kaisafe.ui.home.HomeFragment
kaisafe.data.InstructionDao <|.. kaisafe.data.InstructionDao_Impl
kaisafe.ui.home.AndroidViewModel <|-- kaisafe.ui.home.InstructionViewModel
androidx.appcompat.app.AppCompatActivity <|-- kaisafe.MainActivity
androidx.viewbinding.ViewBinding <|.. kaisafe.databinding.FragmentHomeBinding
kaisafe.ui.home.InstructionAdapter +.. kaisafe.ui.home.InstructionAdapter$ViewHolder
kaisafe.ui.home.ViewHolder <|-- kaisafe.ui.home.InstructionAdapter$ViewHolder
kaisafe.ui.home.Adapter <|-- kaisafe.ui.home.InstructionAdapter
androidx.viewbinding.ViewBinding <|.. kaisafe.databinding.FragmentHomeBinding
androidx.viewbinding.ViewBinding <|.. kaisafe.databinding.FragmentInstructionDetailBinding
kaisafe.ui.home.AndroidViewModel <|-- kaisafe.ui.home.InstructionViewModel
androidx.viewbinding.ViewBinding <|.. kaisafe.databinding.FragmentInstructionDetailBinding
kaisafe.ui.contacts.Fragment <|-- kaisafe.ui.contacts.ContactsFragment
kaisafe.ui.map.ViewModel <|-- kaisafe.ui.map.MapViewModel
kaisafe.data.AppDB <|-- kaisafe.data.AppDB_Impl
androidx.viewbinding.ViewBinding <|.. kaisafe.databinding.FragmentContactsBinding
kaisafe.data.RoomDatabase <|-- kaisafe.data.AppDB
kaisafe.data.AppDB +.. kaisafe.data.AppDB$Companion
androidx.viewbinding.ViewBinding <|.. kaisafe.databinding.FragmentContactsBinding
kaisafe.data.RoomDatabase <|-- kaisafe.data.AppDB
kaisafe.data.AppDB +.. kaisafe.data.AppDB$Companion
androidx.lifecycle.AndroidViewModel <|-- kaisafe.ui.contacts.ContactsViewModel
androidx.fragment.app.Fragment <|-- kaisafe.ui.contacts.ContactsFragment
kaisafe.ui.home.Fragment <|-- kaisafe.ui.home.HomeFragment
androidx.viewbinding.ViewBinding <|.. kaisafe.databinding.ActivityMainBinding
kaisafe.ui.contacts.Adapter <|-- kaisafe.ui.contacts.ContactsAdapter
kaisafe.ui.contacts.ContactsAdapter +.. kaisafe.ui.contacts.ContactsAdapter$ContactViewHolder
kaisafe.ui.contacts.ViewHolder <|-- kaisafe.ui.contacts.ContactsAdapter$ContactViewHolder
kaisafe.data.AppDB <|-- kaisafe.data.AppDB_Impl
kaisafe.ui.contacts.ContactsAdapter +.. kaisafe.ui.contacts.ContactsAdapter$ContactViewHolder
kaisafe.ui.contacts.ViewHolder <|-- kaisafe.ui.contacts.ContactsAdapter$ContactViewHolder
kaisafe.ui.contacts.Adapter <|-- kaisafe.ui.contacts.ContactsAdapter
kaisafe.ui.contacts.AndroidViewModel <|-- kaisafe.ui.contacts.ContactsViewModel
androidx.viewbinding.ViewBinding <|.. kaisafe.databinding.ItemInstructionBinding
kaisafe.ui.map.Fragment <|-- kaisafe.ui.map.MapFragment
kaisafe.data.InstructionDao <|.. kaisafe.data.InstructionDao_Impl
androidx.viewbinding.ViewBinding <|.. kaisafe.databinding.ItemContactBinding
kaisafe.data.ContactDao <|.. kaisafe.data.ContactDao_Impl
androidx.viewbinding.ViewBinding <|.. kaisafe.databinding.FragmentMapBinding
kaisafe.ui.map.ViewModel <|-- kaisafe.ui.map.MapViewModel
kaisafe.ui.home.Fragment <|-- kaisafe.ui.home.HomeFragment
kaisafe.ui.home.Adapter <|-- kaisafe.ui.home.InstructionAdapter
kaisafe.ui.home.InstructionAdapter +.. kaisafe.ui.home.InstructionAdapter$ViewHolder
kaisafe.ui.home.ViewHolder <|-- kaisafe.ui.home.InstructionAdapter$ViewHolder
kaisafe.data.ContactDao <|.. kaisafe.data.ContactDao_Impl
kaisafe.ui.home.Fragment <|-- kaisafe.ui.home.InstructionDetailFragment
androidx.viewbinding.ViewBinding <|.. kaisafe.databinding.ItemInstructionBinding
kaisafe.AppCompatActivity <|-- kaisafe.MainActivity
@enduml